version: '3' # specify docker-compose version

# Define the services/ containers to be run
services:
#    angular:
#      build: /app_public/rubricMaker
#      ports:
#        - "4200:4200" # specify port mapping
#      networks:
#        - rubnet
##      restart: always

    express:
      build: ../HonorsProject
      ports:
        - "3000:3000" #specify ports mapping
      restart: always
      networks:
        - rubnet
      depends_on:
        - mongo

    mongo:
      image: mongo:4
#      environment:
#        MONGO_INITDB_ROOT_USERNAME: root
#        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - "27017:27017" # specify port forwarding
      networks:
        - rubnet

networks:
  rubnet:
    driver: bridge


